name = "Crazy Extraordinary Energy"
author = "Sponeru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1524f50f239f7dc020a16557d92ac6c6f80558bb8e68b6fb5ad2e831dd82d37"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
