name = "Crazy Extraordinary Energy"
author = "Sponeru"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ebfab7afadd44c987bda5f5fe6a985eff857ca2fd8fa747efb023333e7df900"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
